# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: expense_record.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x65xpense_record.proto\x12\x0e\x45xpenseTracker\"Z\n\x07\x45xpense\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x01\x12\x0c\n\x04\x64\x61te\x18\x05 \x01(\t\"\x17\n\x15GetAllExpensesRequest\"C\n\x16GetAllExpensesResponse\x12)\n\x08\x65xpenses\x18\x01 \x03(\x0b\x32\x17.ExpenseTracker.Expense\"@\n\x14\x43reateExpenseRequest\x12(\n\x07\x65xpense\x18\x01 \x01(\x0b\x32\x17.ExpenseTracker.Expense\"A\n\x15\x43reateExpenseResponse\x12(\n\x07\x65xpense\x18\x01 \x01(\x0b\x32\x17.ExpenseTracker.Expense\"L\n\x14UpdateExpenseRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12(\n\x07\x65xpense\x18\x02 \x01(\x0b\x32\x17.ExpenseTracker.Expense\"A\n\x15UpdateExpenseResponse\x12(\n\x07\x65xpense\x18\x01 \x01(\x0b\x32\x17.ExpenseTracker.Expense\"\"\n\x14\x44\x65leteExpenseRequest\x12\n\n\x02id\x18\x01 \x01(\t\"(\n\x15\x44\x65leteExpenseResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x8b\x03\n\x0e\x45xpenseTracker\x12_\n\x0eGetAllExpenses\x12%.ExpenseTracker.GetAllExpensesRequest\x1a&.ExpenseTracker.GetAllExpensesResponse\x12\\\n\rCreateExpense\x12$.ExpenseTracker.CreateExpenseRequest\x1a%.ExpenseTracker.CreateExpenseResponse\x12\\\n\rUpdateExpense\x12$.ExpenseTracker.UpdateExpenseRequest\x1a%.ExpenseTracker.UpdateExpenseResponse\x12\\\n\rDeleteExpense\x12$.ExpenseTracker.DeleteExpenseRequest\x1a%.ExpenseTracker.DeleteExpenseResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'expense_record_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXPENSE']._serialized_start=40
  _globals['_EXPENSE']._serialized_end=130
  _globals['_GETALLEXPENSESREQUEST']._serialized_start=132
  _globals['_GETALLEXPENSESREQUEST']._serialized_end=155
  _globals['_GETALLEXPENSESRESPONSE']._serialized_start=157
  _globals['_GETALLEXPENSESRESPONSE']._serialized_end=224
  _globals['_CREATEEXPENSEREQUEST']._serialized_start=226
  _globals['_CREATEEXPENSEREQUEST']._serialized_end=290
  _globals['_CREATEEXPENSERESPONSE']._serialized_start=292
  _globals['_CREATEEXPENSERESPONSE']._serialized_end=357
  _globals['_UPDATEEXPENSEREQUEST']._serialized_start=359
  _globals['_UPDATEEXPENSEREQUEST']._serialized_end=435
  _globals['_UPDATEEXPENSERESPONSE']._serialized_start=437
  _globals['_UPDATEEXPENSERESPONSE']._serialized_end=502
  _globals['_DELETEEXPENSEREQUEST']._serialized_start=504
  _globals['_DELETEEXPENSEREQUEST']._serialized_end=538
  _globals['_DELETEEXPENSERESPONSE']._serialized_start=540
  _globals['_DELETEEXPENSERESPONSE']._serialized_end=580
  _globals['_EXPENSETRACKER']._serialized_start=583
  _globals['_EXPENSETRACKER']._serialized_end=978
# @@protoc_insertion_point(module_scope)
